<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Room;

class RoomsSeeder extends Seeder
{
    public function run()
    {
        //DB::table('rooms')->truncate(); // Attention ! supprime tout 
        $rooms = [
            ['name' => 'GX15', 'roomNumber' => 'B001', 'capacity' => 2, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317005],
            ['name' => 'After Ski', 'roomNumber' => 'B002', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316625],
            ['name' => 'Tout schuss', 'roomNumber' => 'B003', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316608],
            ['name' => 'Les skibidis', 'roomNumber' => 'B004', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => 316740],
            ['name' => 'les diplômés font du ski', 'roomNumber' => 'B101', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317341],
            ['name' => 'Les crayons', 'roomNumber' => 'B102', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317387],
            ['name' => 'Les Vieux Croutons', 'roomNumber' => 'B103', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317824],
            ['name' => 'Basse Cour', 'roomNumber' => 'B104', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317241],
            ['name' => 'Les Manchots', 'roomNumber' => 'B105', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317798],
            ['name' => 'Les marmottes', 'roomNumber' => 'B106', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317799],
            ['name' => 'Shoop shoop shoop', 'roomNumber' => 'B107', 'capacity' => 3, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317335],
            ['name' => 'Shoop shoop shoop 2', 'roomNumber' => 'B108', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317815],
            ['name' => "L'Asile le retour", 'roomNumber' => 'B109', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317329],
            ['name' => 'Divalanche', 'roomNumber' => 'B110', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316785],
            ['name' => 'Les Golmoncler', 'roomNumber' => 'B111', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316919],
            ['name' => 'Sapins en folie', 'roomNumber' => 'B112', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317179],
            ['name' => 'Skilebo', 'roomNumber' => 'B114', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316701],
            ['name' => "UT'Culsec", 'roomNumber' => 'B116', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317801],
            ['name' => 'WeSkiCoca', 'roomNumber' => 'B118', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317080],
            ['name' => 'Vodkavalanche', 'roomNumber' => 'B120', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317940],
            ['name' => 'Les rois de la glisse', 'roomNumber' => 'B122', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317243],
            ['name' => 'WiskyDefond', 'roomNumber' => 'B124', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317004],
            ['name' => 'Skipute 1', 'roomNumber' => 'B126', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317002],
            ['name' => 'Skipute 2', 'roomNumber' => 'B128', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316529],
            ['name' => 'Bretagne', 'roomNumber' => 'B130', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317032],
            ['name' => 'El Primo', 'roomNumber' => 'B201', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316484],
            ['name' => 'Les Pyrénénés', 'roomNumber' => 'B202', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316526],
            ['name' => 'La Distillerie', 'roomNumber' => 'B204', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317307],
            ['name' => 'Igloo gloo gloo 🐧', 'roomNumber' => 'B205', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317097],
            ['name' => 'Soif\'erie', 'roomNumber' => 'B206', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317084],
            ['name' => 'Keski\'boit', 'roomNumber' => 'B207', 'capacity' => 3, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317806],
            ['name' => 'Meribaize', 'roomNumber' => 'B208', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317741],
            ['name' => 'Les deux appels', 'roomNumber' => 'B209', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316725],
            ['name' => 'Candice Thovex', 'roomNumber' => 'B210', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317325],
            ['name' => 'L\'igloo de luxe', 'roomNumber' => 'B211', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317061],
            ['name' => 'Les stresses', 'roomNumber' => 'B212', 'capacity' => 5, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317208],
            ['name' => 'Les Fromagnons', 'roomNumber' => 'B214', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317377],
            ['name' => 'Patatas bravas', 'roomNumber' => 'B216', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317132],
            ['name' => 'Skiute BRR BRR', 'roomNumber' => 'B218', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317205],
            ['name' => 'Bitouski', 'roomNumber' => 'B220', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317126],
            ['name' => 'Les floconnasses 1', 'roomNumber' => 'B222', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316627],
            ['name' => 'Les Floconnasses 2', 'roomNumber' => 'B224', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317024],
            ['name' => 'Mel Amoi', 'roomNumber' => 'B226', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317102],
            ['name' => 'Le fourrr', 'roomNumber' => 'B228', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316633],
            ['name' => 'Meau', 'roomNumber' => 'B230', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317112],
            ['name' => 'L’abreuvoir & co', 'roomNumber' => 'B301', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316914],
            ['name' => 'Tente Ski', 'roomNumber' => 'B302', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317820],
            ['name' => 'Les gros nibards', 'roomNumber' => 'B303', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317092],
            ['name' => 'The lucky one', 'roomNumber' => 'B304', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317056],
            ['name' => 'Les reconstitués', 'roomNumber' => 'B306', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317338],
            ['name' => 'Bonne descente', 'roomNumber' => 'B308', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316629],
            ['name' => 'Asso 1', 'roomNumber' => 'B312', 'capacity' => 8, 'mood' => '', 'totalPoints' => 0, 'userID' => 317057],
            ['name' => 'Asso 2', 'roomNumber' => 'B314', 'capacity' => 4, 'mood' => '', 'totalPoints' => 0, 'userID' => 316366],
            ['name' => 'Asso 3', 'roomNumber' => 'B316', 'capacity' => 8, 'mood' => '', 'totalPoints' => 0, 'userID' => 317285],
            ['name' => 'Asso 4', 'roomNumber' => 'B318', 'capacity' => 8, 'mood' => '', 'totalPoints' => 0, 'userID' => 317225],
            ['name' => 'Prout', 'roomNumber' => 'B402', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317122],
            ['name' => 'La Cabane A Pastis', 'roomNumber' => 'B404', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317370],
            ['name' => 'Slay loop', 'roomNumber' => 'A008', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => 317016],
            ['name' => 'Girlies', 'roomNumber' => 'A010', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => 317393],
            ['name' => 'OLAF 1', 'roomNumber' => 'A101', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317038],
            ['name' => 'Vroom', 'roomNumber' => 'A103', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316467],
            ['name' => 'Crâne crâne crâne', 'roomNumber' => 'A104', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => 317388],
            ['name' => 'Alvin et les chips molles', 'roomNumber' => 'A105', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316450],
            ['name' => 'Naughteam', 'roomNumber' => 'A106', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => 317044],
            ['name' => 'Les vins Chauds Givrés', 'roomNumber' => 'A107', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316695],
            ['name' => 'Teuse', 'roomNumber' => 'A108', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316829],
            ['name' => 'Kilapang LâchE la Chaussette', 'roomNumber' => 'A109', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316462],
            ['name' => 'La Swannerie et les plaisantins', 'roomNumber' => 'A110', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317804],
            ['name' => 'Les 4 neurones', 'roomNumber' => 'A111', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317840],
            ['name' => 'Les disciples de Laura', 'roomNumber' => 'A112', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317797],
            ['name' => 'Sliding Woks', 'roomNumber' => 'A114', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => 317849],
            ['name' => 'ScotlandUnitedTourdefranceCompagny', 'roomNumber' => 'A116', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316471],
            ['name' => 'Skigloo', 'roomNumber' => 'A118', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316599],
            ['name' => 'Les Touristes', 'roomNumber' => 'A201', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317315],
            ['name' => 'Les Cools Kids A La Neige', 'roomNumber' => 'A202', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317357],
            ['name' => 'Smokette', 'roomNumber' => 'A203', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317115],
            ['name' => 'Juraski park', 'roomNumber' => 'A204', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316720],
            ['name' => 'Les dégénérés', 'roomNumber' => 'A205', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316439],
            ['name' => 'Last Dance', 'roomNumber' => 'A206', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317397],
            ['name' => 'The Brainrot Cavaliers', 'roomNumber' => 'A207', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316891],
            ['name' => 'Pap est riz', 'roomNumber' => 'A208', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316620],
            ['name' => 'Igloo Polyglotte', 'roomNumber' => 'A209', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316896],
            ['name' => 'La grande descente', 'roomNumber' => 'A210', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316482],
            ['name' => 'tire bouchon et tire fesses', 'roomNumber' => 'A211', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317211],
            ['name' => 'La montagne à la montagne', 'roomNumber' => 'A212', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317791],
            ['name' => 'Basic Shit', 'roomNumber' => 'A213', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317857],
            ['name' => 'Dah\'ut', 'roomNumber' => 'A214', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317105],
            ['name' => 'L\'avachambre', 'roomNumber' => 'A216', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316631], 
            /*['name' => 'GX15', 'roomNumber' => 'B001', 'capacity' => 2, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'After Ski', 'roomNumber' => 'B002', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Tout schuss', 'roomNumber' => 'B003', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les skibidis', 'roomNumber' => 'B004', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'les diplômés font du ski', 'roomNumber' => 'B101', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les crayons', 'roomNumber' => 'B102', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les Vieux Croutons', 'roomNumber' => 'B103', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Basse Cour', 'roomNumber' => 'B104', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les Manchots', 'roomNumber' => 'B105', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les marmottes', 'roomNumber' => 'B106', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Shoop shoop shoop', 'roomNumber' => 'B107', 'capacity' => 3, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Shoop shoop shoop 2', 'roomNumber' => 'B108', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => "L'Asile le retour", 'roomNumber' => 'B109', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Divalanche', 'roomNumber' => 'B110', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les Golmoncler', 'roomNumber' => 'B111', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Sapins en folie', 'roomNumber' => 'B112', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Skilebo', 'roomNumber' => 'B114', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => "UT'Culsec", 'roomNumber' => 'B116', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'WeSkiCoca', 'roomNumber' => 'B118', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Vodkavalanche', 'roomNumber' => 'B120', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les rois de la glisse', 'roomNumber' => 'B122', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'WiskyDefond', 'roomNumber' => 'B124', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Skipute 1', 'roomNumber' => 'B126', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Skipute 2', 'roomNumber' => 'B128', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Bretagne', 'roomNumber' => 'B130', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'El Primo', 'roomNumber' => 'B201', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les Pyrénénés', 'roomNumber' => 'B202', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'La Distillerie', 'roomNumber' => 'B204', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Igloo gloo gloo 🐧', 'roomNumber' => 'B205', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Soif\'erie', 'roomNumber' => 'B206', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Keski\'boit', 'roomNumber' => 'B207', 'capacity' => 3, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Meribaize', 'roomNumber' => 'B208', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les deux appels', 'roomNumber' => 'B209', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Candice Thovex', 'roomNumber' => 'B210', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'L\'igloo de luxe', 'roomNumber' => 'B211', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les stresses', 'roomNumber' => 'B212', 'capacity' => 5, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les Fromagnons', 'roomNumber' => 'B214', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Patatas bravas', 'roomNumber' => 'B216', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Skiute BRR BRR', 'roomNumber' => 'B218', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Bitouski', 'roomNumber' => 'B220', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les floconnasses 1', 'roomNumber' => 'B222', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les Floconnasses 2', 'roomNumber' => 'B224', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Mel Amoi', 'roomNumber' => 'B226', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Le fourrr', 'roomNumber' => 'B228', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Meau', 'roomNumber' => 'B230', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'L’abreuvoir & co', 'roomNumber' => 'B301', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Tente Ski', 'roomNumber' => 'B302', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les gros nibards', 'roomNumber' => 'B303', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'The lucky one', 'roomNumber' => 'B304', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les reconstitués', 'roomNumber' => 'B306', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Bonne descente', 'roomNumber' => 'B308', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Asso 1', 'roomNumber' => 'B312', 'capacity' => 8, 'mood' => '', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Asso 2', 'roomNumber' => 'B314', 'capacity' => 4, 'mood' => '', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Asso 3', 'roomNumber' => 'B316', 'capacity' => 8, 'mood' => '', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Asso 4', 'roomNumber' => 'B318', 'capacity' => 8, 'mood' => '', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Prout', 'roomNumber' => 'B402', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'La Cabane A Pastis', 'roomNumber' => 'B404', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Slay loop', 'roomNumber' => 'A008', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Girlies', 'roomNumber' => 'A010', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'OLAF 1', 'roomNumber' => 'A101', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Vroom', 'roomNumber' => 'A103', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Crâne crâne crâne', 'roomNumber' => 'A104', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Alvin et les chips molles', 'roomNumber' => 'A105', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Naughteam', 'roomNumber' => 'A106', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les vins Chauds Givrés', 'roomNumber' => 'A107', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Teuse', 'roomNumber' => 'A108', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Kilapang LâchE la Chaussette', 'roomNumber' => 'A109', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'La Swannerie et les plaisantins', 'roomNumber' => 'A110', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les 4 neurones', 'roomNumber' => 'A111', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les disciples de Laura', 'roomNumber' => 'A112', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Sliding Woks', 'roomNumber' => 'A114', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'ScotlandUnitedTourdefranceCompagny', 'roomNumber' => 'A116', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Skigloo', 'roomNumber' => 'A118', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les Touristes', 'roomNumber' => 'A201', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les Cools Kids A La Neige', 'roomNumber' => 'A202', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Smokette', 'roomNumber' => 'A203', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Juraski park', 'roomNumber' => 'A204', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Les dégénérés', 'roomNumber' => 'A205', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Last Dance', 'roomNumber' => 'A206', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'The Brainrot Cavaliers', 'roomNumber' => 'A207', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Pap est riz', 'roomNumber' => 'A208', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Igloo Polyglotte', 'roomNumber' => 'A209', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'La grande descente', 'roomNumber' => 'A210', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'tire bouchon et tire fesses', 'roomNumber' => 'A211', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'La montagne à la montagne', 'roomNumber' => 'A212', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Basic Shit', 'roomNumber' => 'A213', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'Dah\'ut', 'roomNumber' => 'A214', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],
            ['name' => 'L\'avachambre', 'roomNumber' => 'A216', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null],*/
        ];

        /*foreach ($rooms as $room) {
            Room::create($room);
        }*/
        foreach ($rooms as $room) {
            DB::table('rooms')
                ->where('roomNumber', $room['roomNumber'])
                ->update([
                    'userID' => $room['userID'],
                    //'name' => $room['name'], 
                ]);
        }
    }
}