<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Room;

class RoomsSeeder extends Seeder
{
    public function run()
    {
        //DB::table('rooms')->truncate(); // Attention ! supprime tout 
        $rooms = [
            ['name' => 'GX15', 'roomNumber' => 'B001', 'capacity' => 2, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317005, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'After Ski', 'roomNumber' => 'B002', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316625, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Tout schuss', 'roomNumber' => 'B003', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316608, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les skibidis', 'roomNumber' => 'B004', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => 316740, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'les diplômés font du ski', 'roomNumber' => 'B101', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317341, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les crayons', 'roomNumber' => 'B102', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317387, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Vieux Croutons', 'roomNumber' => 'B103', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317824, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Basse Cour', 'roomNumber' => 'B104', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317241, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Manchots', 'roomNumber' => 'B105', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317798, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les marmottes', 'roomNumber' => 'B106', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317799, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Shoop shoop shoop', 'roomNumber' => 'B107', 'capacity' => 3, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317335, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Shoop shoop shoop 2', 'roomNumber' => 'B108', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317815, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => "L'Asile le retour", 'roomNumber' => 'B109', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317329, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Divalanche', 'roomNumber' => 'B110', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316785, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Golmoncler', 'roomNumber' => 'B111', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316919, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Sapins en folie', 'roomNumber' => 'B112', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317179, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Skilebo', 'roomNumber' => 'B114', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316701, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => "UT'Culsec", 'roomNumber' => 'B116', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317801, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'WeSkiCoca', 'roomNumber' => 'B118', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317080, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Vodkavalanche', 'roomNumber' => 'B120', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317940, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les rois de la glisse', 'roomNumber' => 'B122', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317243, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'WiskyDefond', 'roomNumber' => 'B124', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317004, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Skipute 1', 'roomNumber' => 'B126', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317002, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Skipute 2', 'roomNumber' => 'B128', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316529, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Bretagne', 'roomNumber' => 'B130', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317032, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'El Primo', 'roomNumber' => 'B201', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316484, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Pyrénénés', 'roomNumber' => 'B202', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316526, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'La Distillerie', 'roomNumber' => 'B204', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317307, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Igloo gloo gloo 🐧', 'roomNumber' => 'B205', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317097, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Soif\'erie', 'roomNumber' => 'B206', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317084, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Keski\'boit', 'roomNumber' => 'B207', 'capacity' => 3, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317806, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Meribaize', 'roomNumber' => 'B208', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317741, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les deux appels', 'roomNumber' => 'B209', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316725, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Candice Thovex', 'roomNumber' => 'B210', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317325, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'L\'igloo de luxe', 'roomNumber' => 'B211', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317061, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les stresses', 'roomNumber' => 'B212', 'capacity' => 5, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317208, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Fromagnons', 'roomNumber' => 'B214', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317377, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Patatas bravas', 'roomNumber' => 'B216', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317132, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Skiute BRR BRR', 'roomNumber' => 'B218', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317205, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Bitouski', 'roomNumber' => 'B220', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317126, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les floconnasses 1', 'roomNumber' => 'B222', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316627, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Floconnasses 2', 'roomNumber' => 'B224', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317024, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Mel Amoi', 'roomNumber' => 'B226', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317102, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Le fourrr', 'roomNumber' => 'B228', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316633, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Meau', 'roomNumber' => 'B230', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317112, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'L’abreuvoir & co', 'roomNumber' => 'B301', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316914, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Tente Ski', 'roomNumber' => 'B302', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317820, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les gros nibards', 'roomNumber' => 'B303', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317092, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'The lucky one', 'roomNumber' => 'B304', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317056, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les reconstitués', 'roomNumber' => 'B306', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317338, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Bonne descente', 'roomNumber' => 'B308', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316629, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Asso 1', 'roomNumber' => 'B312', 'capacity' => 8, 'mood' => '', 'totalPoints' => 0, 'userID' => 317057, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Asso 2', 'roomNumber' => 'B314', 'capacity' => 4, 'mood' => '', 'totalPoints' => 0, 'userID' => 316366, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Asso 3', 'roomNumber' => 'B316', 'capacity' => 8, 'mood' => '', 'totalPoints' => 0, 'userID' => 317285, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Asso 4', 'roomNumber' => 'B318', 'capacity' => 8, 'mood' => '', 'totalPoints' => 0, 'userID' => 317225, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Prout', 'roomNumber' => 'B402', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317122, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'La Cabane A Pastis', 'roomNumber' => 'B404', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317370, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Slay loop', 'roomNumber' => 'A008', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => 317016, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Girlies', 'roomNumber' => 'A010', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => 317393, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'OLAF 1', 'roomNumber' => 'A101', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317038, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Vroom', 'roomNumber' => 'A103', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316467, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Crâne crâne crâne', 'roomNumber' => 'A104', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => 317388, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Alvin et les chips molles', 'roomNumber' => 'A105', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316450, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Naughteam', 'roomNumber' => 'A106', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => 317044, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les vins Chauds Givrés', 'roomNumber' => 'A107', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316695, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Teuse', 'roomNumber' => 'A108', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316829, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Kilapang LâchE la Chaussette', 'roomNumber' => 'A109', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316462, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'La Swannerie et les plaisantins', 'roomNumber' => 'A110', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317804, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les 4 neurones', 'roomNumber' => 'A111', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317840, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les disciples de Laura', 'roomNumber' => 'A112', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317797, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Sliding Woks', 'roomNumber' => 'A114', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => 317849, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'ScotlandUnitedTourdefranceCompagny', 'roomNumber' => 'A116', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316471, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Skigloo', 'roomNumber' => 'A118', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 316599, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Touristes', 'roomNumber' => 'A201', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317315, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Cools Kids A La Neige', 'roomNumber' => 'A202', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317357, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Smokette', 'roomNumber' => 'A203', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317115, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Juraski park', 'roomNumber' => 'A204', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316720, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les dégénérés', 'roomNumber' => 'A205', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316439, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Last Dance', 'roomNumber' => 'A206', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317397, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'The Brainrot Cavaliers', 'roomNumber' => 'A207', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316891, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Pap est riz', 'roomNumber' => 'A208', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316620, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Igloo Polyglotte', 'roomNumber' => 'A209', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316896, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'La grande descente', 'roomNumber' => 'A210', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 316482, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'tire bouchon et tire fesses', 'roomNumber' => 'A211', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => 317211, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'La montagne à la montagne', 'roomNumber' => 'A212', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317791, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Basic Shit', 'roomNumber' => 'A213', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => 317857, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Dah\'ut', 'roomNumber' => 'A214', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 317105, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'L\'avachambre', 'roomNumber' => 'A216', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => 316631, 'photoPath' => null, 'description' => null, 'passions' => null],


            /*['name' => 'GX15', 'roomNumber' => 'B001', 'capacity' => 2, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'After Ski', 'roomNumber' => 'B002', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Tout schuss', 'roomNumber' => 'B003', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les skibidis', 'roomNumber' => 'B004', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'les diplômés font du ski', 'roomNumber' => 'B101', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les crayons', 'roomNumber' => 'B102', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Vieux Croutons', 'roomNumber' => 'B103', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Basse Cour', 'roomNumber' => 'B104', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Manchots', 'roomNumber' => 'B105', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les marmottes', 'roomNumber' => 'B106', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Shoop shoop shoop', 'roomNumber' => 'B107', 'capacity' => 3, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Shoop shoop shoop 2', 'roomNumber' => 'B108', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => "L'Asile le retour", 'roomNumber' => 'B109', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Divalanche', 'roomNumber' => 'B110', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Golmoncler', 'roomNumber' => 'B111', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Sapins en folie', 'roomNumber' => 'B112', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Skilebo', 'roomNumber' => 'B114', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => "UT'Culsec", 'roomNumber' => 'B116', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'WeSkiCoca', 'roomNumber' => 'B118', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Vodkavalanche', 'roomNumber' => 'B120', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les rois de la glisse', 'roomNumber' => 'B122', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'WiskyDefond', 'roomNumber' => 'B124', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Skipute 1', 'roomNumber' => 'B126', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Skipute 2', 'roomNumber' => 'B128', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Bretagne', 'roomNumber' => 'B130', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'El Primo', 'roomNumber' => 'B201', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Pyrénénés', 'roomNumber' => 'B202', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'La Distillerie', 'roomNumber' => 'B204', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Igloo gloo gloo 🐧', 'roomNumber' => 'B205', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Soif\'erie', 'roomNumber' => 'B206', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Keski\'boit', 'roomNumber' => 'B207', 'capacity' => 3, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Meribaize', 'roomNumber' => 'B208', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les deux appels', 'roomNumber' => 'B209', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Candice Thovex', 'roomNumber' => 'B210', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'L\'igloo de luxe', 'roomNumber' => 'B211', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les stresses', 'roomNumber' => 'B212', 'capacity' => 5, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Fromagnons', 'roomNumber' => 'B214', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Patatas bravas', 'roomNumber' => 'B216', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Skiute BRR BRR', 'roomNumber' => 'B218', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Bitouski', 'roomNumber' => 'B220', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les floconnasses 1', 'roomNumber' => 'B222', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Floconnasses 2', 'roomNumber' => 'B224', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Mel Amoi', 'roomNumber' => 'B226', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Le fourrr', 'roomNumber' => 'B228', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Meau', 'roomNumber' => 'B230', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'L’abreuvoir & co', 'roomNumber' => 'B301', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Tente Ski', 'roomNumber' => 'B302', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les gros nibards', 'roomNumber' => 'B303', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'The lucky one', 'roomNumber' => 'B304', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les reconstitués', 'roomNumber' => 'B306', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Bonne descente', 'roomNumber' => 'B308', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Asso 1', 'roomNumber' => 'B312', 'capacity' => 8, 'mood' => '', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Asso 2', 'roomNumber' => 'B314', 'capacity' => 4, 'mood' => '', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Asso 3', 'roomNumber' => 'B316', 'capacity' => 8, 'mood' => '', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Asso 4', 'roomNumber' => 'B318', 'capacity' => 8, 'mood' => '', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Prout', 'roomNumber' => 'B402', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'La Cabane A Pastis', 'roomNumber' => 'B404', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Slay loop', 'roomNumber' => 'A008', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Girlies', 'roomNumber' => 'A010', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'OLAF 1', 'roomNumber' => 'A101', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Vroom', 'roomNumber' => 'A103', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Crâne crâne crâne', 'roomNumber' => 'A104', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Alvin et les chips molles', 'roomNumber' => 'A105', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Naughteam', 'roomNumber' => 'A106', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les vins Chauds Givrés', 'roomNumber' => 'A107', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Teuse', 'roomNumber' => 'A108', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Kilapang LâchE la Chaussette', 'roomNumber' => 'A109', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'La Swannerie et les plaisantins', 'roomNumber' => 'A110', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les 4 neurones', 'roomNumber' => 'A111', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les disciples de Laura', 'roomNumber' => 'A112', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Sliding Woks', 'roomNumber' => 'A114', 'capacity' => 4, 'mood' => '--', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'ScotlandUnitedTourdefranceCompagny', 'roomNumber' => 'A116', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Skigloo', 'roomNumber' => 'A118', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Touristes', 'roomNumber' => 'A201', 'capacity' => 6, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les Cools Kids A La Neige', 'roomNumber' => 'A202', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Smokette', 'roomNumber' => 'A203', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Juraski park', 'roomNumber' => 'A204', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Les dégénérés', 'roomNumber' => 'A205', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Last Dance', 'roomNumber' => 'A206', 'capacity' => 6, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'The Brainrot Cavaliers', 'roomNumber' => 'A207', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Pap est riz', 'roomNumber' => 'A208', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Igloo Polyglotte', 'roomNumber' => 'A209', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'La grande descente', 'roomNumber' => 'A210', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'tire bouchon et tire fesses', 'roomNumber' => 'A211', 'capacity' => 4, 'mood' => '-', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'La montagne à la montagne', 'roomNumber' => 'A212', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Basic Shit', 'roomNumber' => 'A213', 'capacity' => 4, 'mood' => '++', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'Dah\'ut', 'roomNumber' => 'A214', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],
            ['name' => 'L\'avachambre', 'roomNumber' => 'A216', 'capacity' => 4, 'mood' => '+', 'totalPoints' => 0, 'userID' => null, 'photoPath' => null, 'description' => null, 'passions' => null],*/
        ];

        /*foreach ($rooms as $room) {
            Room::create($room);
        }*/
        foreach ($rooms as $room) {
            DB::table('rooms')
                ->where('roomNumber', $room['roomNumber'])
                ->update([
                    'userID' => $room['userID'],
                    //'name' => $room['name'], 
                ]);
        }
    }
}