stages:
  - integration

integration_test:
  stage: integration
  allow_failure: true
  tags:
    - docker-skiut
  script:
    - apk update && apk add curl
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker stop app || true
    - docker rm app || true
    - docker run -d -p 8090:80 --name app "$CI_REGISTRY_IMAGE:latest"
    - docker cp .env.ci app:/var/www/html/.env
    - sleep 10
    - curl --fail http://localhost:8090 || (docker logs app && exit 1)
    - docker stop app && docker rm app

