stages:
  - integration

integration_test:
  stage: integration
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  tags:
    - docker-skiut
  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker stop app || true
    - docker rm app || true
    - docker run -d -p 8090:80 --name app "$CI_REGISTRY_IMAGE:latest"
    - docker cp .env.ci app:/var/www/html/.env
    - sleep 10
    - docker exec app curl --fail http://localhost || (docker logs app && exit 1)
    - docker stop app && docker rm app
  only:
    - main

