stages:
  - integration

integration_test:
  stage: integration
  allow_failure: true
  tags:
    - docker-skiut
  script:
    - apk update && apk add curl
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker stop app || true
    - docker rm app || true
    - docker run -d -p 8090:80 --name app -v $(pwd)/.env.ci:/var/www/html/.env "$CI_REGISTRY_IMAGE:latest"
    - docker exec app php artisan jwt:generate
    - sleep 10
    - export APP_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' app)
    - curl --fail "http://$APP_IP/" || (docker logs app && exit 1)
    - docker stop app && docker rm app

