stages:
  - build

build_with_kaniko:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]
  tags:
    - docker
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor \
        --context "$CI_PROJECT_DIR" \
        --dockerfile "$CI_PROJECT_DIR/Dockerfile" \
        --destination "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" \
        --destination "$CI_REGISTRY_IMAGE:latest"
  only:
    - main

#laravel_tests:
#  stage: test
#  image: php:8.3
#  tags:
#  - docker
#  - linux
#  services:
#    - mysql:8.0
#  variables:
#    DB_HOST: mysql
#    DB_DATABASE: test_db
#    DB_USERNAME: root
#    DB_PASSWORD: root
#  before_script:
#    - apt-get update && apt-get install -y unzip git libzip-dev libpng-dev libonig-dev libxml2-dev zip
#    - docker-php-ext-install pdo pdo_mysql mbstring zip
#    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
#    - composer install --no-interaction --prefer-dist
#    - cp .env.testing .env
#    - php artisan key:generate
#    - php artisan migrate --force
#  script:
#    - php artisan test
#  only:
#    - merge_requests
#    - main
#    - develop
