stages:
  - integration

variables:
  PROJECT_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest  # <- image complète ici

integration_test:
  stage: integration
  tags:
    - docker-skiut
  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker run -d -p 8090:80 --name app "$PROJECT_IMAGE_TAG"
    - docker cp .env.ci app:/var/www/html/.env
    - sleep 10
    - curl --fail http://localhost:8090 || (docker logs app && exit 1)
    - docker stop app && docker rm app
