stages:
  - integration

variables:
  PROJECT_IMAGE_TAG: skiutc/server-skiut-2026:latest

integration_test:
  stage: integration
  tags:
    - docker-skiut  # Assure-toi que ce tag est bien celui du runner que tu viens de tester
  script:
    - docker run -d -p 8080:80 --name app "$PROJECT_IMAGE_TAG"
    - docker cp .env.ci app:/var/www/html/.env
    - sleep 10
    - curl --fail http://localhost:8080 || (docker logs app && exit 1)
    - docker stop app && docker rm app