services:
  app:
    #image: registry.gitlab.utc.fr/skiutc/server-skiut-2026
    build: .
    container_name: laravel-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:80"
    env_file:
      - .env.local
    networks:
      - skiut-net

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: skiut
      MYSQL_USER: skiut_user
      MYSQL_PASSWORD: skiut_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - skiut-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"    # Accès web via http://localhost:8081
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_pass
    networks:
      - skiut-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - skiut-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - skiut-net

volumes:
  db-data:

networks:
  skiut-net:
