version: '3.8'

services:
  app:
    image: php:8.3-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./app/.env:/var/www/html/.env  # Mount the .env file to the container
    networks:
      - laravel_network
    depends_on:
      - db
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
      - DB_CONNECTION=mysql
      - DB_HOST=sql.mde.utc
      - DB_PORT=3306
      - DB_DATABASE=skiutc
      - DB_USERNAME=skiutc
      - DB_PASSWORD=T@GvXDOv6@xQN[Bu
      - CACHE_STORE=database
      - SESSION_DRIVER=database
      - OAUTH_URL=https://auth.assos.utc.fr
      - OAUTH_CLIENT_ID=storage_path('app/public/OAuthClientId.txt')
      - OAUTH_CLIENT_SECRET=storage_path('app/private/OAuthClientSecret.txt')
      - JWT_PRIVATE_KEY_PATH=app/private/private.pem
      - JWT_PUBLIC_KEY_PATH=app/public/public.pem
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
      - MAIL_FROM_ADDRESS="skiutc@assos.utc.fr"
      - MAIL_FROM_NAME="${APP_NAME}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app
    working_dir: /var/www/html/public  # Point to the public directory

  db:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: skiutc
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: skiutc
      MYSQL_PASSWORD: T@GvXDOv6@xQN[Bu  # Match the DB_PASSWORD from .env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  dbdata:
    driver: local

networks:
  laravel_network:
    driver: bridge
